### PR TITLE
filesystem is not resized when restoring from snapshot/cloning to larger size than origin

### LINKED ISSUE #85: Resize filesystem of a larger volume created from a snapshot/volume
Upstream [issue](https://github.com/kubernetes/kubernetes/issues/94929) introduces improvements to volume resizing. The change added new resize code and moved to [kubernetes/mount-utils](https://github.com/kubernetes/mount-utils). 

This change should be reflected in all CSI drivers. New module should be imported and it's resize logic added. 

Dependency should be updated to use the current k8s/mount-utils module and CSI driver should use the resize code it provides in NodeStageVolume to perform the resize if needed. Example of similar change can be found [here](https://github.com/kubernetes/cloud-provider-openstack/pull/1563/files)

Issue originated in [BZ1877261](https://bugzilla.redhat.com/show_bug.cgi?id=1877261)

#### How to reproduce:
1. create original pod and pvc
2. create snapshot from original pvc
3. create pvc from the snapshot specifying larger size than the original
4. create pod to consume the new pvc
5. observe fs size of the new volume inside the pod does not match the requested size

### PR DESCRIPTION
**Pull request by RomanBednar**
Resolves #85

Sanity tests need to be disabled (or fixed) first: https://github.com/kubernetes/test-infra/pull/27795

### CODE REVIEW

File: pkg/ibmcsidriver/ibm_csi_driver_test.go [hunk 1]
```diff
@@ -55,6 +65,64 @@ func initIBMCSIDriver(t *testing.T) *IBMCSIDriver {
 	return icDriver
 }
 
+// FakeNodeMounterWithCustomActions ...
```
Comment (RomanBednar) [inline pkg/ibmcsidriver/ibm_csi_driver_test.go:68]: This should maybe move here? https://github.com/IBM/ibm-csi-common/blob/b1ab7008f8e435da0f0f507c4890adc48c805133/pkg/mountmanager/fake-safe-mounter.go#L25

**Comment by RomanBednar** [comment]
@arahamad-zz PTAL as well since you might have more context about it.

**Comment by ambiknai** [comment]
With our existing driver, I was not able to recreate the issue

```
 
➜  demo oc describe pvc restore-pvc1                                                                                  
Name:          restore-pvc1
Namespace:     default
StorageClass:  ibmc-vpc-block-10iops-tier
Status:        Bound
Volume:        pvc-806bb7e6-698f-4c4d-befe-95c25d61638c
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
               volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      100Gi
Access Modes:  RWO
VolumeMode:    Filesystem
DataSource:
  APIGroup:  snapshot.storage.k8s.io
  Kind:      VolumeSnapshot
  Name:      snapshot-csi-block-6
Used By:     <none>
Events:
  Type    Reason                 Age                 From                                                                                      Message
  ----    ------                 ----                ----                                                                                      -------
  Normal  Provisioning           103s                vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_b34802ae-3391-4835-815a-a405ea593912  External provisioner is provisioning volume for claim "default/restore-pvc1"
  Normal  ExternalProvisioning   60s (x4 over 103s)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "vpc.block.csi.ibm.io" or manually created by system administrator
  Normal  ProvisioningSucceeded  55s                 vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_b34802ae-3391-4835-815a-a405ea593912  Successfully provisioned volume pvc-806bb7e6-698f-4c4d-befe-95c25d61638c
➜  demo oc get pvc                                                                                                    
NAME                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
csi-block-pvc-custom-one   Bound    pvc-ade48371-4627-4660-9b30-75e7171a8381   10Gi       RWO            ibmc-vpc-block-5iops-tier    43h
restore-pvc1               Bound    pvc-806bb7e6-698f-4c4d-befe-95c25d61638c   100Gi      RWO            ibmc-vpc-block-10iops-tier   108s
➜  demo oc create -f podtwo.yaml 
deployment.apps/podtwo created


➜  demo oc get pods
NAME                         READY   STATUS    RESTARTS   AGE
podtwo-59f696d697-xb88s      1/1     Running   0          79s
testcustom-cfd587b66-rbq2p   1/1     Running   0          4m51s
➜  demo oc exec -it podtwo-59f696d697-xb88s  /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@podtwo-59f696d697-xb88s:/# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda    252:0    0  100G  0 disk 
|-vda1 252:1    0    1G  0 part 
`-vda2 252:2    0   99G  0 part /etc/resolv.conf
vdb    252:16   0  372K  0 disk 
vdc    252:32   0   44K  0 disk 
vdd    252:48   0   10G  0 disk 
vde    252:64   0  100G  0 disk /myvolumepath
root@podtwo-59f696d697-xb88s:/# oc describe pod podtwo-59f696d697-xb88s
bash: oc: command not found
root@podtwo-59f696d697-xb88s:/# exit
exit
command terminated with exit code 127
➜  demo oc describe pod podtwo-59f696d697-xb88s
Name:         podtwo-59f696d697-xb88s
Namespace:    default
Priority:     0
Node:         10.240.0.55/10.240.0.55
Start Time:   Wed, 02 Nov 2022 10:57:47 +0530
Labels:       app=podtwo
              pod-template-hash=59f696d697
Annotations:  cni.projectcalico.org/containerID: 4827e3bf290fce03eaf302efcf188b64943ce968f3f5fe5831d39d5c3742e6a9
              cni.projectcalico.org/podIP: 172.17.211.39/32
              cni.projectcalico.org/podIPs: 172.17.211.39/32
Status:       Running
IP:           172.17.211.39
IPs:
  IP:           172.17.211.39
Controlled By:  ReplicaSet/podtwo-59f696d697
Containers:
  container-name:
    Container ID:   containerd://2367233072c99e668c5cdf2d727e4e79f1d2c86499bd900aebfb236fdf8b33e5
    Image:          nginx
    Image ID:       docker.io/library/nginx@sha256:943c25b4b66b332184d5ba6bb18234273551593016c0e0ae906bab111548239f
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 02 Nov 2022 10:58:58 +0530
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /myvolumepath from pvc-name (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jnd2h (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  pvc-name:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  restore-pvc1
    ReadOnly:   false
  kube-api-access-jnd2h:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 600s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 600s
Events:
  Type    Reason                  Age    From                     Message
  ----    ------                  ----   ----                     -------
  Normal  Scheduled               3m34s  default-scheduler        Successfully assigned default/podtwo-59f696d697-xb88s to 10.240.0.55
  Normal  SuccessfulAttachVolume  2m27s  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-806bb7e6-698f-4c4d-befe-95c25d61638c"
  Normal  Pulling                 2m24s  kubelet                  Pulling image "nginx"
  Normal  Pulled                  2m23s  kubelet                  Successfully pulled image "nginx" in 479.047887ms
  Normal  Created                 2m23s  kubelet                  Created container container-name
  Normal  Started                 2m23s  kubelet                  Started container container-name
➜  demo 
➜  demo oc get pvc                   
NAME                       STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
csi-block-pvc-custom-one   Bound     pvc-ade48371-4627-4660-9b30-75e7171a8381   10Gi       RWO            ibmc-vpc-block-5iops-tier    43h
restore-pvc1               Pending                                                                        ibmc-vpc-block-10iops-tier   30s
➜  demo oc describe pvc restore-pvc1 
Name:          restore-pvc1
Namespace:     default
StorageClass:  ibmc-vpc-block-10iops-tier
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
               volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
DataSource:
  APIGroup:  snapshot.storage.k8s.io
  Kind:      VolumeSnapshot
  Name:      snapshot-csi-block-6
Used By:     <none>
Events:
  Type    Reason                Age               From                                                                                      Message
  ----    ------                ----              ----                                                                                      -------
  Normal  Provisioning          34s               vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_b34802ae-3391-4835-815a-a405ea593912  External provisioner is provisioning volume for claim "default/restore-pvc1"
  Normal  ExternalProvisioning  6s (x3 over 34s)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "vpc.block.csi.ibm.io" or manually created by system administrator
➜  demo oc describe pvc restore-pvc1 
Name:          restore-pvc1
Namespace:     default
StorageClass:  ibmc-vpc-block-10iops-tier
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
               volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
DataSource:
  APIGroup:  snapshot.storage.k8s.io
  Kind:      VolumeSnapshot
  Name:      snapshot-csi-block-6
Used By:     <none>
Events:
  Type    Reason                Age                From                                                                                      Message
  ----    ------                ----               ----                                                                                      -------
  Normal  Provisioning          38s                vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_b34802ae-3391-4835-815a-a405ea593912  External provisioner is provisioning volume for claim "default/restore-pvc1"
  Normal  ExternalProvisioning  10s (x3 over 38s)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "vpc.block.csi.ibm.io" or manually created by system administrator
➜  demo oc describe pvc restore-pvc1 
Name:          restore-pvc1
Namespace:     default
StorageClass:  ibmc-vpc-block-10iops-tier
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
               volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
DataSource:
  APIGroup:  snapshot.storage.k8s.io
  Kind:      VolumeSnapshot
  Name:      snapshot-csi-block-6
Used By:     <none>
Events:
  Type    Reason                Age                From                                                                                      Message
  ----    ------                ----               ----                                                                                      -------
  Normal  Provisioning          41s                vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_b34802ae-3391-4835-815a-a405ea593912  External provisioner is provisioning volume for claim "default/restore-pvc1"
  Normal  ExternalProvisioning  13s (x3 over 41s)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "vpc.block.csi.ibm.io" or manually created by system administrator
➜  demo oc describe pvc restore-pvc1 
Name:          restore-pvc1
Namespace:     default
StorageClass:  ibmc-vpc-block-10iops-tier
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
               volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
DataSource:
  APIGroup:  snapshot.storage.k8s.io
  Kind:      VolumeSnapshot
  Name:      snapshot-csi-block-6
Used By:     <none>
Events:
  Type    Reason                Age               From                                                                                      Message
  ----    ------                ----              ----                                                                                      -------
  Normal  Provisioning          44s               vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_b34802ae-3391-4835-815a-a405ea593912  External provisioner is provisioning volume for claim "default/restore-pvc1"
  Normal  ExternalProvisioning  1s (x4 over 44s)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "vpc.block.csi.ibm.io" or manually created by system administrator
➜  demo kubectl logs -n kube-system ibm-vpc-block-csi-controller-0  -c iks-vpc-block-driver > iks-vpc-block-driver.log 
➜  demo kubectl logs -n kube-system ibm-vpc-block-csi-controller-0  -c iks-vpc-block-driver > iks-vpc-block-driver.log
➜  demo oc describe pvc restore-pvc1                                                                                  
Name:          restore-pvc1
Namespace:     default
StorageClass:  ibmc-vpc-block-10iops-tier
Status:        Bound
Volume:        pvc-806bb7e6-698f-4c4d-befe-95c25d61638c
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
               volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      100Gi
Access Modes:  RWO
VolumeMode:    Filesystem
DataSource:
  APIGroup:  snapshot.storage.k8s.io
  Kind:      VolumeSnapshot
  Name:      snapshot-csi-block-6
Used By:     <none>
Events:
  Type    Reason                 Age                 From                                                                                      Message
  ----    ------                 ----                ----                                                                                      -------
  Normal  Provisioning           103s                vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_b34802ae-3391-4835-815a-a405ea593912  External provisioner is provisioning volume for claim "default/restore-pvc1"
  Normal  ExternalProvisioning   60s (x4 over 103s)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "vpc.block.csi.ibm.io" or manually created by system administrator
  Normal  ProvisioningSucceeded  55s                 vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_b34802ae-3391-4835-815a-a405ea593912  Successfully provisioned volume pvc-806bb7e6-698f-4c4d-befe-95c25d61638c
➜  demo oc get pvc                                                                                                    
NAME                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
csi-block-pvc-custom-one   Bound    pvc-ade48371-4627-4660-9b30-75e7171a8381   10Gi       RWO            ibmc-vpc-block-5iops-tier    43h
restore-pvc1               Bound    pvc-806bb7e6-698f-4c4d-befe-95c25d61638c   100Gi      RWO            ibmc-vpc-block-10iops-tier   108s
➜  demo oc create -f podtwo.yaml 
deployment.apps/podtwo created
➜  demo oc get pods
NAME                         READY   STATUS              RESTARTS   AGE
podtwo-59f696d697-xb88s      0/1     ContainerCreating   0          56s
testcustom-cfd587b66-rbq2p   1/1     Running             0          4m28s
➜  demo oc get pods
NAME                         READY   STATUS              RESTARTS   AGE
podtwo-59f696d697-xb88s      0/1     ContainerCreating   0          60s
testcustom-cfd587b66-rbq2p   1/1     Running             0          4m32s
➜  demo oc get pods
NAME                         READY   STATUS              RESTARTS   AGE
podtwo-59f696d697-xb88s      0/1     ContainerCreating   0          63s
testcustom-cfd587b66-rbq2p   1/1     Running             0          4m35s
➜  demo oc get pods
NAME                         READY   STATUS              RESTARTS   AGE
podtwo-59f696d697-xb88s      0/1     ContainerCreating   0          66s
testcustom-cfd587b66-rbq2p   1/1     Running             0          4m38s
➜  demo oc get pods
NAME                         READY   STATUS    RESTARTS   AGE
podtwo-59f696d697-xb88s      1/1     Running   0          79s
testcustom-cfd587b66-rbq2p   1/1     Running   0          4m51s
➜  demo oc exec -it podtwo-59f696d697-xb88s  /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@podtwo-59f696d697-xb88s:/# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda    252:0    0  100G  0 disk 
|-vda1 252:1    0    1G  0 part 
`-vda2 252:2    0   99G  0 part /etc/resolv.conf
vdb    252:16   0  372K  0 disk 
vdc    252:32   0   44K  0 disk 
vdd    252:48   0   10G  0 disk 
vde    252:64   0  100G  0 disk /myvolumepath
root@podtwo-59f696d697-xb88s:/# oc describe pod podtwo-59f696d697-xb88s
bash: oc: command not found
root@podtwo-59f696d697-xb88s:/# exit
exit
command terminated with exit code 127
➜  demo oc describe pod podtwo-59f696d697-xb88s
Name:         podtwo-59f696d697-xb88s
Namespace:    default
Priority:     0
Node:         10.240.0.55/10.240.0.55
Start Time:   Wed, 02 Nov 2022 10:57:47 +0530
Labels:       app=podtwo
              pod-template-hash=59f696d697
Annotations:  cni.projectcalico.org/containerID: 4827e3bf290fce03eaf302efcf188b64943ce968f3f5fe5831d39d5c3742e6a9
              cni.projectcalico.org/podIP: 172.17.211.39/32
              cni.projectcalico.org/podIPs: 172.17.211.39/32
Status:       Running
IP:           172.17.211.39
IPs:
  IP:           172.17.211.39
Controlled By:  ReplicaSet/podtwo-59f696d697
Containers:
  container-name:
    Container ID:   containerd://2367233072c99e668c5cdf2d727e4e79f1d2c86499bd900aebfb236fdf8b33e5
    Image:          nginx
    Image ID:       docker.io/library/nginx@sha256:943c25b4b66b332184d5ba6bb18234273551593016c0e0ae906bab111548239f
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 02 Nov 2022 10:58:58 +0530
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /myvolumepath from pvc-name (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jnd2h (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  pvc-name:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  restore-pvc1
    ReadOnly:   false
  kube-api-access-jnd2h:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 600s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 600s
Events:
  Type    Reason                  Age    From                     Message
  ----    ------                  ----   ----                     -------
  Normal  Scheduled               3m34s  default-scheduler        Successfully assigned default/podtwo-59f696d697-xb88s to 10.240.0.55
  Normal  SuccessfulAttachVolume  2m27s  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-806bb7e6-698f-4c4d-befe-95c25d61638c"
  Normal  Pulling                 2m24s  kubelet                  Pulling image "nginx"
  Normal  Pulled                  2m23s  kubelet                  Successfully pulled image "nginx" in 479.047887ms
  Normal  Created                 2m23s  kubelet                  Created container container-name
  Normal  Started                 2m23s  kubelet                  Started container container-name
  ```

File: pkg/ibmcsidriver/node.go [hunk 2]
```diff
@@ -543,10 +550,16 @@ func (su *VolumeStatUtils) IsDevicePathNotExist(devicePath string) bool {
...
 
 // Resize expands the fs
-func (volMountUtils *VolumeMountUtils) Resize(mounter mountmanager.Mounter, devicePath string, deviceMountPath string) (bool, error) {
-	r := mount.NewResizeFs(mounter.NewSafeFormatAndMount().Exec)
-	if _, err := r.Resize(devicePath, deviceMountPath); err != nil {
-		return false, err
+func (volMountUtils *VolumeMountUtils) Resize(mounter *mount.SafeFormatAndMount, devicePath string, deviceMountPath string) (bool, error) {
+	r := mount.NewResizeFs(mounter.Exec)
+	needResize, err := r.NeedResize(devicePath, deviceMountPath)
+	if err != nil {
```
[the remark this answers is not in the document]
Comment (RomanBednar) [reply pkg/ibmcsidriver/node.go:556]: Resizing in `NodeExpandVolume()` is not the issue here. We need to do the resize in `NodeStageVolume()`. This is because when you restore from a snapshot to a new PVC the expand function never gets called since this is not expand operation in fact. In other words we need to check the filesystem during staging and resize if needed.

If you read my commit messages from first to last it should explain different parts of the changes - the change here is a separate commit that just improves resizing to be "smarter" and do the resize only if needed. It has nothing to do with the original bug.

**Comment by RomanBednar** [comment]
> With our existing driver, I was not able to recreate the issue
> 
> Could you please help to explain why this change is required.

You probably did recreate the issue but looking at the output you did not check the filesystem size of the PVC restored from snapshot - that's where the problem is. Use `df` to check filesystem size, you can't see that with `lsblk`. For more details check the Bugzilla that's linked in the issue https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/issues/85 (if needed).

**Comment by ambiknai** [comment]
Thanks @RomanBednar  . I am going to pull this code, build an image and do e2e in our CSI driver.

**Comment by ambiknai** [comment]
I have verified e2e functionality and works as expected. @arahamad  could you pls take a look in to the PR once.

File: pkg/ibmcsidriver/node.go [hunk 3]
```diff
@@ -44,10 +46,11 @@ import (
 
 // CSINodeServer ...
 type CSINodeServer struct {
-	Driver   *IBMCSIDriver
-	Mounter  mountmanager.Mounter
-	Metadata nodeMetadata.NodeMetadata
-	Stats    StatsUtils
+	Driver             *IBMCSIDriver
+	Mounter            mountmanager.Mounter
```
Comment (arahamad) [inline pkg/ibmcsidriver/node.go:50]: with this code changes `Mounter` will not be useful, I see we can utilise `Mounter` by implementing this PR logic in https://github.com/IBM/ibm-csi-common repo

@ambiknai , can you check the possibility for this so that we will have a mounter as a package with interface

File: pkg/ibmcsidriver/node.go [hunk 4]
```diff
@@ -302,11 +305,15 @@ func (csiNS *CSINodeServer) NodeStageVolume(ctx context.Context, req *csi.NodeSt
 
 	// FormatAndMount will format only if needed
 	ctxLogger.Info("Formating and mounting ", zap.String("source", source), zap.String("stagingTargetPath", stagingTargetPath), zap.String("fsType", fsType), zap.Reflect("options", options))
-	err = csiNS.Mounter.NewSafeFormatAndMount().FormatAndMount(source, stagingTargetPath, fsType, options)
+	err = csiNS.SafeFormatAndMount.FormatAndMount(source, stagingTargetPath, fsType, options)
 	if err != nil {
 		return nil, commonError.GetCSIError(ctxLogger, commonError.FormatAndMountFailed, requestID, err, source, stagingTargetPath)
 	}
 
+	if _, err := mountmgr.Resize(csiNS.SafeFormatAndMount, devicePath, stagingTargetPath); err != nil {
```
Comment (arahamad) [inline pkg/ibmcsidriver/node.go:313]: This will not be change if we implement new changes in https://github.com/IBM/ibm-csi-common lib

**Review by arahamad — CHANGES_REQUESTED** [review]
just see if you can implement these changes in https://github.com/IBM/ibm-csi-common which will require very less changes in this repo

File: pkg/ibmcsidriver/node.go (hunk 4 above)
Comment (RomanBednar) [reply pkg/ibmcsidriver/node.go:313]: Surely the logic can move to this lib. But it will require quite a few changes to the current lib code as well to allow command faking. Basically what I tried to do here was to avoid calling this constructor here (`NewSafeFormatAndMount()`) and call it only once driver is being constructed because that's where the fakes get in.

So if I understand it well to keep this behavior in the lib then  [this](https://github.com/IBM/ibm-csi-common/blob/master/pkg/mountmanager/safe-mounter.go#L31) would have to move [here](https://github.com/IBM/ibm-csi-common/blob/fe384106592ad5b5586aff5dfdc1c89fd52a4ee3/pkg/mountmanager/safe-mounter.go#L44).

And then ofcourse it would make sense to move the "custom faker" there as well as I [wrote before](https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/pull/100/files/528af8273e1c45fdd5f515340fff36497dd0dd67#r1001816301).

Comment (arahamad) [reply pkg/ibmcsidriver/node.go:313]: sure @RomanBednar , actually as of now we have two safeFormatAndMount objectand only one of them is useful, that one reason another let the code be in previous format. I asked @ambiknai to check the possibility to move this code to lib for me it can we done.

Comment (ambiknai) [reply pkg/ibmcsidriver/node.go:313]: @RomanBednar  Sorry it took some time to get back on this PR. ? Would it be  possible for you to contribute  above discussed changes in [IBM/ibm-csi-common ](https://github.com/IBM/ibm-csi-common) repo

Comment (ambiknai) [reply pkg/ibmcsidriver/node.go:313]: FYI, test-infra PR for sanity is merged .

Comment (RomanBednar) [reply pkg/ibmcsidriver/node.go:313]: @ambiknai Sure, I'll take a look.

**Comment by RomanBednar** [comment]
Tested on real cluster to verify resizing works in current version of the patch:

```
$ oc get pvc/pvc-1-snapshot-restore && oc exec pod/example-2 -- df -h | grep nginx
NAME                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
pvc-1-snapshot-restore   Bound    pvc-7326acb8-ff75-44aa-82e2-ba159b2bd9a8   20Gi       RWO            ibmc-vpc-block-10iops-tier   4m7s
/dev/vde         20G   28M   20G   1% /usr/share/nginx/html
```

Tests here will fail until the changes are merged in [library](https://github.com/IBM/ibm-csi-common) and version [here](https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/blob/1a6b9b5a5413e05568defda471585929443d8fda/go.mod#L6) gets bumped. @arahamad and @ambiknai PTAL and review again.

**Comment by ambiknai** [comment]
@RomanBednar  New release created - https://github.com/IBM/ibm-csi-common/releases/tag/v1.1.2

Could you please do necessary changes in this PR to use `Resize` logic from `ibm-csi-common` repo. `Resize`  method from this codebase can be removed.

**Comment by ambiknai** [comment]
@RomanBednar  Could you change ibm-csi-common version to new release - https://github.com/IBM/ibm-csi-common/releases/tag/v1.1.3

File: pkg/ibmcsidriver/node.go (hunk 3 above)
Comment (RomanBednar) [reply pkg/ibmcsidriver/node.go]: @arashad @ambiknai thank you for cooperation, I believe we're done with the mounter changes.

**Comment by RomanBednar** [comment]
> @RomanBednar Could you change ibm-csi-common version to new release - https://github.com/IBM/ibm-csi-common/releases/tag/v1.1.3

@ambiknai Done.

**Review by arahamad — APPROVED** [review]
/lgtm

please verify changes as well

**Review by ambiknai — APPROVED** [review]
/lgtm

**Comment by RomanBednar** [comment]
/hold cancel

https://github.com/IBM/ibm-csi-common/pull/69 is now merged.
